import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

function humanize(key: string) { return key.replaceAll("_", " ").replace(/^./, (c) => c.toUpperCase()); }

export default async function IntentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const { data: intent } = await supabase.from("intents").select("id,type,status,summary,constraints,missing_information,confidence,source_text,conversation_id,project_id,created_at,updated_at").eq("id", id).single(); if (!intent) notFound(); const constraints = (intent.constraints ?? {}) as Record<string, unknown>; const missing = Array.isArray(intent.missing_information) ? intent.missing_information : [];
  return <main className="detailShell"><header className="detailHeader"><Link className="backLink" href="/intents">← Intents</Link><div className="brandLockup compact"><span className="brandGlyph">✦</span><strong>ELYNVIA</strong></div></header><section className="intentDetail"><div className="intentHero"><p className="eyebrow">INTENT · {intent.type.toUpperCase()}</p><h1>{intent.summary}</h1><div className="intentStatus"><span>{intent.status}</span>{intent.confidence != null && <span>{Math.round(Number(intent.confidence) * 100)}% understood</span>}</div></div>{intent.source_text && <section className="detailPanel sourcePanel"><small>ORIGINAL REQUEST</small><p>“{intent.source_text}”</p></section>}<div className="projectColumns"><section className="detailPanel"><div className="panelHeading"><span className="panelIcon">✓</span><div><small>STRUCTURED CONTEXT</small><h3>What ELYNVIA understood</h3></div></div>{Object.keys(constraints).length ? <dl className="dataList">{Object.entries(constraints).map(([key,value]) => <div key={key}><dt>{humanize(key)}</dt><dd>{String(value)}</dd></div>)}</dl> : <p className="emptyState">No structured constraints yet.</p>}</section><section className="detailPanel"><div className="panelHeading"><span className="panelIcon violetIcon">?</span><div><small>NEXT CLARIFICATIONS</small><h3>What could make this better</h3></div></div>{missing.length ? <ul className="missingList">{missing.map((item) => <li key={String(item)}>{humanize(String(item))}</li>)}</ul> : <p className="successState">✓ The essential information detected by the current engine is present.</p>}</section></div><div className="detailActions">{intent.conversation_id && <Link className="primaryLink" href={`/conversations/${intent.conversation_id}`}>Open conversation →</Link>}{intent.project_id && <Link className="secondaryLink" href={`/projects/${intent.project_id}`}>Open project →</Link>}</div></section></main>;
}
