import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { promoteIntentToProject, replyToIntent } from "@/app/actions";
import { createClient } from "@/lib/supabase/server";

const clarificationLabels: Record<string, string> = { departure_location: "Where would you like to depart from?", destination: "Which destination do you have in mind?", budget: "What budget would you like to stay within?", date: "When would you like this to happen?" };

export default async function ConversationPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const [{ data: conversation }, { data: messages }, { data: intents }] = await Promise.all([supabase.from("conversations").select("id,title,project_id,created_at").eq("id", id).single(), supabase.from("messages").select("id,role,content,created_at").eq("conversation_id", id).order("created_at"), supabase.from("intents").select("id,type,status,summary,constraints,missing_information,confidence,project_id").eq("conversation_id", id).order("created_at", { ascending: false })]);
  if (!conversation) notFound(); const intent = intents?.[0]; const missing = Array.isArray(intent?.missing_information) ? intent.missing_information : []; const clarification = missing.length ? clarificationLabels[String(missing[0])] ?? `Could you clarify: ${String(missing[0])}?` : null;
  return <main className="detailShell conversationWorkspace"><header className="detailHeader"><Link className="backLink" href="/conversations">← Conversations</Link><div className="brandLockup compact"><span className="brandGlyph">✦</span><strong>ELYNVIA</strong></div></header><section className="detailGrid"><div className="conversationPanel"><div className="conversationHeading"><p className="eyebrow">CONVERSATION</p><h1>{conversation.title || "New intention"}</h1><p>Keep talking naturally. ELYNVIA keeps the structured intent alongside the conversation.</p></div><div className="messageStream">{messages?.map((message) => <article className={`message ${message.role}`} key={message.id}><small>{message.role === "user" ? "YOU" : "ELYNVIA"}</small><p>{message.content}</p></article>)}{clarification && intent ? <article className="message assistant"><small>ELYNVIA · NEXT QUESTION</small><p>{clarification}</p><form className="replyComposer" action={replyToIntent}><input type="hidden" name="conversation_id" value={conversation.id}/><input type="hidden" name="intent_id" value={intent.id}/><input name="reply" required maxLength={10000} autoComplete="off" placeholder="Reply naturally…"/><button className="primaryButton" type="submit">Send →</button></form></article> : <article className="message assistant completeMessage"><small>ELYNVIA</small><p>I have enough information to move this intention forward.</p></article>}</div></div><aside className="intentPanel"><p className="eyebrow">LIVE INTENT</p>{intent ? <><div className="intentStatus"><span>{intent.type}</span><span>{intent.status}</span></div><h2>What I understand</h2><p className="intentSummary">{intent.summary}</p><div className="confidenceMetric"><strong>{intent.confidence != null ? `${Math.round(Number(intent.confidence) * 100)}%` : "—"}</strong><span>understanding confidence</span></div><dl><dt>Detected constraints</dt><dd><pre>{JSON.stringify(intent.constraints, null, 2)}</pre></dd><dt>Still useful to know</dt><dd>{missing.length ? missing.join(", ") : "Nothing essential is missing"}</dd></dl>{intent.project_id || conversation.project_id ? <p className="successState">✓ Connected to a project</p> : <form action={promoteIntentToProject}><input type="hidden" name="intent_id" value={intent.id}/><input type="hidden" name="conversation_id" value={conversation.id}/><button className="primaryButton fullButton" type="submit">Turn into a project →</button></form>}<p className="betaNote">Intent Engine foundation · designed so the AI engine can evolve without changing your core data contract.</p></> : <div className="emptyPanel compactEmpty"><span className="emptyGlyph">◎</span><h2>Understanding…</h2><p>No structured intent was found yet.</p></div>}</aside></section></main>;
}
