import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export default async function ProjectDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login");
  const [{ data: project }, { data: intents }, { data: conversations }] = await Promise.all([supabase.from("projects").select("id,title,status,description,created_at,updated_at").eq("id", id).single(), supabase.from("intents").select("id,type,status,summary,confidence,conversation_id,created_at").eq("project_id", id).order("created_at", { ascending: false }), supabase.from("conversations").select("id,title,status,updated_at").eq("project_id", id).order("updated_at", { ascending: false })]); if (!project) notFound();
  return <main className="detailShell"><header className="detailHeader"><Link className="backLink" href="/projects">← Projects</Link><div className="brandLockup compact"><span className="brandGlyph">✦</span><strong>ELYNVIA</strong></div></header><section className="projectDetail"><div className="projectHero"><div><p className="eyebrow">ELYNVIA PROJECT</p><h1>{project.title}</h1><p>{project.description || "A living project created from an ELYNVIA intention."}</p></div><div className="projectState"><span className="statusDot"/><strong>{project.status}</strong><small>Updated {new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(project.updated_at))}</small></div></div><div className="projectStats"><article><strong>{intents?.length ?? 0}</strong><span>Linked intents</span></article><article><strong>{conversations?.length ?? 0}</strong><span>Conversations</span></article><article><strong>Private</strong><span>Workspace</span></article></div><div className="projectColumns"><section className="railCard"><div className="railTitle"><h3>Linked intents</h3><span>{intents?.length ?? 0}</span></div>{intents?.length ? intents.map((intent) => <Link className="railRow linkRow" href={`/intents/${intent.id}`} key={intent.id}><div><strong>{intent.summary}</strong><small>{intent.type} · {intent.status}{intent.confidence != null ? ` · ${Math.round(Number(intent.confidence) * 100)}%` : ""}</small></div><span>→</span></Link>) : <p className="emptyState">No linked intents yet.</p>}</section><section className="railCard"><div className="railTitle"><h3>Conversations</h3><span>{conversations?.length ?? 0}</span></div>{conversations?.length ? conversations.map((conversation) => <Link className="railRow linkRow" href={`/conversations/${conversation.id}`} key={conversation.id}><div><strong>{conversation.title || "Conversation"}</strong><small>{conversation.status}</small></div><span>→</span></Link>) : <p className="emptyState">No linked conversations yet.</p>}</section></div></section></main>;
}
